EXP_NAME: "SwinT"

RESUME_WEIGHT: ~

DISTRIBUTED: True

WEIGHT:
  NAME: "swinT.pth"
  SAVE_DIR: "/mnt/sdb/data/wangxinran/weight/fgvclib"

LOGGER:
  NAME: "txt_logger"

DATASET:
  NAME: "CUB_200_2011"
  ROOT: "/mnt/sdb/data/wangxinran/dataset/"
  TRAIN:
    BATCH_SIZE: 4
    POSITIVE: 0
    PIN_MEMORY: True
    SHUFFLE: True
    NUM_WORKERS: 4
    DROP_LAST: True
  TEST:
    BATCH_SIZE: 4
    POSITIVE: 0
    PIN_MEMORY: True
    SHUFFLE: False
    NUM_WORKERS: 4
    DROP_LAST: False

MODEL:
  NAME: "ViT_NeT"
  CLASS_NUM: 200
  ARGS:
    - pretrained: True
    - mixup_alpha: 0.8
    - cutmix_alpha: 1.0
    - cutmix_minmax: null
    - prob: 1.0
    - switch_prob: 0.5
    - mode: 'batch'
    - label_smoothing: 0.1
  CRITERIONS:
    - name: "soft_target_cross_entropy_loss"
      args: []
      w: 1.0
  BACKBONE:
    NAME: "swin_base_patch4_window14_448" 
    ARGS:
      - pretrained: True
      - window_size: 14
      - embed_dim: 128
      - depths: [ 2, 2, 18, 2 ]
      - num_heads: [ 4, 8, 16, 32 ]
      - img_size: 448
      - num_classes: 200
  ENCODER:
    NAME: ~
  NECKS:
    NAME: ~
  HEADS:
    NAME: "dtree"
    ARGS:
      - depth: 4
      - proto_size: [1,1]    

TRANSFORMS:
  TRAIN:
    - name: "resize"
      size:
        - 448
        - 448
    - name: "to_tensor"
    - name: "normalize"
      mean:
         - 0.485
         - 0.456
         - 0.406
      std:
        - 0.229
        - 0.224
        - 0.225
  TEST:
    - name: "resize"
      size:
        - 600
        - 600
    - name: "center_crop"
      size: 
        - 448
        - 448      
    - name: "to_tensor"
    - name: "normalize"
      mean:
         - 0.485
         - 0.456
         - 0.406
      std:
        - 0.229
        - 0.224
        - 0.225

OPTIMIZER:
  NAME: "AdamW"
  ARGS: 
    - weight_decay: 1.0e-08
    - eps: 1.0e-08
    - betas: 
        - 0.9
        - 0.999
  LR:
    base: 6.25e-06
    backbone: 6.25e-06
    encoder: 6.25e-06
    necks: 6.25e-06
    heads: 6.25e-06  

LR_SCHEDULE:
  NAME: "cosine_warmup_schedule"
  ARGS: 
    - warmup_epochs: 1
    - decay_epochs: 30
    - min_lr: 6.25e-08
    - warmup_lr: 6.25e-09

ITERATION_NUM: ~
EPOCH_NUM: 30
START_EPOCH: 15
AMP: True
UPDATE_STRATEGY: "vit_update_strategy"

# Validation details
PER_ITERATION: ~
PER_EPOCH: ~
METRICS:
  - name: "accuracy(topk=1)"
    metric: "accuracy"
    top_k: 1
    threshold: ~
  - name: "accuracy(topk=5)"
    metric: "accuracy"
    top_k: 5
    threshold: ~
  - name: "recall(threshold=0.5)"
    metric: "recall"
    top_k: ~
    threshold: 0.5
  - name: "precision(threshold=0.5)"
    metric: "precision"
    top_k: ~
    threshold: 0.5
  