EXP_NAME: "Mutual-Channel-Loss"

RESUME_WEIGHT: None

WEIGHT:
  NAME: "mutual_channel_loss_vgg166.pth"
  SAVE_DIR: "/data/wangxinran/models/fgvclib/"

LOGGER: 
  NAME: "TxtLogger"

DATASETS:
  ROOT: "/data/wangxinran/dataset/Birds2"
  TRAIN: 
    BATCH_SIZE: 32
    POSITIVE: None
    PIN_MEMORY: True
    SHUFFLE: True
    NUM_WORKERS: 4
  TEST: 
    BATCH_SIZE: 32
    POSITIVE: None
    PIN_MEMORY: False
    SHUFFLE: False
    NUM_WORKERS: 4

MODEL:
  NAME: "MCL"
  CLASS_NUM: 200
  CRITERIONS: 
  - name: "mutual_channel_loss"
    args: 
      - height: 14
      - cnum: 3
      - div_weight: 20
      - dis_weight: 1.5
    w: 1.0
  - name: "cross_entropy_loss"
    args: []
    w: 1.0
  BACKBONE:
    NAME: "vgg16"
    ARGS: 
      - pretrained: True
      - del_keys: 
        - "features.21.weight"
        - "features.21.bias"
        - "features.24.weight"
        - "features.28.weight"
        - "features.28.bias"
  ENCODING:
    NAME: "MaxPool2d"
    ARGS: 
      - kernel_size: 2
      - stride: 2
  NECKS:
    NAME: None
  HEADS:
    NAME: "classifier_2fc"
    ARGS:
      - in_dim: 
        - 29400
      - hid_dim: 512
  OUTPUTS_NUM: None

TRANSFORMS: 
  TRAIN: 
    - name: "resize"
      size: 
        - 224
        - 224
    - name: "random_crop"
      size: 224
      padding: 4
    - name: "random_horizontal_flip"
      prob: 0.5
    - name: "to_tensor"
    - name: "normalize"
      mean: 
         - 0.5
         - 0.5
         - 0.5
      std: 
        - 0.5
        - 0.5
        - 0.5
  TEST:
    - name: "resize"
      size: 
        - 224
        - 224
    - name: "to_tensor"
    - name: "normalize"
      mean: 
         - 0.5
         - 0.5
         - 0.5
      std: 
        - 0.5
        - 0.5
        - 0.5

OPTIMIZER:
  NAME: SGD
  MOMENTUM: 0.9
  LR: 
    backbone: 0.001
    encoding: 0.01
    necks: 0.01
    heads: 0.01

ITERATION_NUM: None
EPOCH_NUM: 200
START_EPOCH: 0
UPDATE_STRATEGY: "general_updating"

# Validation details
PER_ITERATION: None
PER_EPOCH: None
METRICS: 
  - "top1-accuracy"